[versions]
agp = "8.12.0-rc01"
atomicfu = "0.29.0"
billing = "8.0.0"
biometric = "1.2.0-alpha05"
datastorePreferences = "1.1.7"
dnsjava = "3.6.3"
hilt = "2.57"
hiltCompiler = "1.2.0"
hiltAndroidCompiler = "2.57"
hiltNavigationCompose = "1.2.0"
kotlin = "2.2.0"
kotlinxSerializationJson = "1.9.0"
ksp = "2.2.0-2.0.2"
pcap4jCore = "1.8.2"
retrofit = "3.0.0"
shizuku-api = "13.1.5"
shizuku-provider = "13.1.5"
room = "2.7.2"
activityCompose = "1.10.1"
coreKtx = "1.16.0"
coreSplashscreen = "1.0.1"
compose = "1.7.8"
material3 = "1.3.2"
navigationCompose = "2.9.2"
appcompat = "1.7.1"
workRuntimeKtx = "2.10.2"
hiltCommon = "1.2.0"

[libraries]
# DataStore
androidx-biometric = { module = "androidx.biometric:biometric", version.ref = "biometric" }
androidx-core = { module = "androidx.core:core", version.ref = "coreKtx" }
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastorePreferences" }
androidx-hilt-work = { module = "androidx.hilt:hilt-work", version.ref = "hiltCompiler" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
androidx-room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }

androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
androidx-core-splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "coreSplashscreen" }

# Compose
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
androidx-compose-material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended", version.ref = "compose" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigationCompose" }


#Hilt
atomicfu = { module = "org.jetbrains.kotlinx:atomicfu", version.ref = "atomicfu" }
billing = { module = "com.android.billingclient:billing", version.ref = "billing" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
converter-scalars = { module = "com.squareup.retrofit2:converter-scalars", version.ref = "retrofit" }
dnsjava = { module = "dnsjava:dnsjava", version.ref = "dnsjava" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hiltAndroidCompiler" }
hilt-compile = { module = "androidx.hilt:hilt-compiler", version.ref = "hiltCompiler"}
hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hiltAndroidCompiler" }
hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hiltNavigationCompose" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
pcap4j-core = { module = "org.pcap4j:pcap4j-core", version.ref = "pcap4jCore" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
shizuku-api = { module = "dev.rikka.shizuku:api", version.ref = "shizuku-api" }
shizuku-provider = { module = "dev.rikka.shizuku:provider", version.ref = "shizuku-provider" }
androidx-work-runtime-ktx = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "workRuntimeKtx" }
androidx-hilt-common = { group = "androidx.hilt", name = "hilt-common", version.ref = "hiltCommon" }

[plugins]
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
android-application = { id = "com.android.application", version.ref = "agp" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
